name: Deploy to 
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./static
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2


    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 'ftp.wakandastreamers.com.br'
        ftp-username: 'wakandastreamers'
        ftp-password: 'tjuDRSWwkARJ'
        local-dir: ./static/
        server-dir: /home/wakandastreamers/admin.wakandastreamers.com.br