name: Deploy to 
on:
  push:
jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.wakandastreamers.com.br
          username: wakandastreamers
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftps