name: DemoNewCD
on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'wakandastreamers'
          server: 'ftp.wakandastreamers.com.br'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './static/*'
          remote_path: '/home/wakandastreamers/wakandastreamers.com.br'
          args: '-o ConnectTimeout=5'