name: Build and Deploy
on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Archive production Artifact
        uses: actions/upload-artifact@main
        with:
          name: static
          path: static
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.SFTP_SERVER }}
          FTP_USERNAME: ${{ secrets.SFTP_USER }}
          FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          LOCAL_DIR: ./static
          REMOTE_DIR: /home/wakandastreamers/wakandastreamers.com.br/env/stg
          METHOD: sftp
          PORT: 22


    
    


