name: Deploy to 
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./static
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2


    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.SFTP_SERVER }}
        ftp-username: ${{ secrets.SFTP_USER }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: ./static/